#!/bin/bash

# This script was generated by distribution_script_generator.py
# Script 3 of 3 (addresses 501-531)

export TOKEN_TYPE='0xb481310100f9f9b812de1fb45b8e118f69c6b69e59145bef34b2232efdd7a8e5::sail_test::SAIL_TEST'
export METHOD='0x9af1bff168d5155c2628a29ea17e7012353d94bf7173900461143d096079d96e::minter::mint_test_sail'
export PUBLISHER='0xc8f1a6f24d265297be826001677ac5d2209070f7f3b8d17f7ccbd075c289a3f3'
export MINTER='0xb145981a29c220d8ac1523a512f423eeedce0b71279c7aca0ec005642a1f7431'
export CLOCK=0x6
sui client ptb \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin500 \
--transfer-objects '[coin500]' @0x9541b03f9a663dee2bf9570618432f81babdae1d01b8002c5846c7fe666df872 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin501 \
--transfer-objects '[coin501]' @0x9cb2eb2937063e4129580bdee3f916e9717f1d40994413e5cd4fdc4668bf885c \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin502 \
--transfer-objects '[coin502]' @0xc2c42d4b02066bce3d86202a7f9a30257b41d1b4b9eb16f19078c884dcca38f9 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin503 \
--transfer-objects '[coin503]' @0x92c4119ae4e8304dd64ad2409ff3bba284f10b3c91666afc12f174bc12ed0190 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin504 \
--transfer-objects '[coin504]' @0x6fd21e399e0b57add54e04b58ebe81bad2cd17a8770036de74c6c716593ef8c2 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin505 \
--transfer-objects '[coin505]' @0x22f5a9253f38af67a5271fd5c4e6bae45954bfe2a8a75a4269c47d893c1664e5 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin506 \
--transfer-objects '[coin506]' @0x7fdc56994fbef1edab33e7c3de571e9dd51329b0f3e4b265de5e72a28474c299 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin507 \
--transfer-objects '[coin507]' @0xc08db07d8b125f28583f52957606a092569017df7a573252e7d12bf59b607f1b \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin508 \
--transfer-objects '[coin508]' @0x5b9a0719881f3fb4abbba813769c9e4897ff00220c232fdcf9d1c86799856421 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin509 \
--transfer-objects '[coin509]' @0xd19bdff08493bcd21f61d85e8678a6571c0551f6c19ff681c227eaeaa73c5311 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin510 \
--transfer-objects '[coin510]' @0x34dbe0889c394430add49283079a10d8526a927d8e00fe4460011cc5545da95c \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin511 \
--transfer-objects '[coin511]' @0xe64d7c86aecb83d242255c15fa331ac2dac97d322dad418cf91b218730b0cdef \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin512 \
--transfer-objects '[coin512]' @0xc12b9e51374be91392ccfa647a87c0e73e96bbf970b4b0c92bc3e993de61e202 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin513 \
--transfer-objects '[coin513]' @0x7a730f11e20de6671f8c7b11cd30b6e98309ecaa43efaffdd07725560b54c5c3 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin514 \
--transfer-objects '[coin514]' @0x4f3f090a72b662096aef2a74f4163708f09b60e188302fac50a5f06d3b9b5208 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin515 \
--transfer-objects '[coin515]' @0x42a23f1f24c68342f19f5a27dac5b56f9712fd5d9c80d79b3b78b0c9cd947108 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin516 \
--transfer-objects '[coin516]' @0x46e4e69db86741c3b574c15cafb1ea37eb8f2184b7856ee6135f5031e257d984 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin517 \
--transfer-objects '[coin517]' @0x4ce8d348419b23bb4bfd865560281fe4dc65a4d8219427c6de234ae6f5a1397c \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin518 \
--transfer-objects '[coin518]' @0x886f7d6af6d835b20633f6637663e114db806ef46b0d81ad2bbf925bc147bf87 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin519 \
--transfer-objects '[coin519]' @0x789a6b11f284c636aac97837e0aaebb00195eaceb49e65825d58bf33babfcd10 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin520 \
--transfer-objects '[coin520]' @0xa16d1aac1cd9d341b6bb95682d218bc93d2d1fc9291500dd65fe9159f4f928a5 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin521 \
--transfer-objects '[coin521]' @0x5d4cb2b65c912ab387ca4838045db6782d8d6ccc644b063e69d58b3913ffa3ba \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin522 \
--transfer-objects '[coin522]' @0x8c66a6cb2b124d32626d0bd1d7c5344f03988e626c2c6f6490b5fccbb03c9307 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin523 \
--transfer-objects '[coin523]' @0x1235c8e64a26eedeb163b65911fc347e1981ac570d4eae2aed3602db0533b2c8 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin524 \
--transfer-objects '[coin524]' @0x1245ba93a417cc8d268b693d5e4ce758fe9db3615fc89be574f1c2a6370af2cc \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin525 \
--transfer-objects '[coin525]' @0xf631dc85e07890457d74e0b6166c1e530b19adbfbc23b4d65fa00ff6c015de6c \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin526 \
--transfer-objects '[coin526]' @0xf3dccb8ccf5881abed9283ab5b15284c7e18ee9b17b25a09b17de75c6e747595 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin527 \
--transfer-objects '[coin527]' @0xf3e37b467dc1ea960291b166d4ec587c290f857a417dfd4565824b82974af94c \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin528 \
--transfer-objects '[coin528]' @0x05e060703036516dc6b0e50a8ce3c0f3d4db8d08c271c810db13dcf0afa9b592 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 3000000000 @$CLOCK \
--assign coin529 \
--transfer-objects '[coin529]' @0x83a842d23198101dc1322c76054beb9393b1125c7c15058cf16a4ec8ba424a4d \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin530 \
--transfer-objects '[coin530]' @0x2b4530c2f633c29d6f90227137941dd0120f4b1c9143a153197bdf86e965abd2
