#!/bin/bash

# This script was generated by distribution_script_generator.py

export TOKEN_TYPE='0xb481310100f9f9b812de1fb45b8e118f69c6b69e59145bef34b2232efdd7a8e5::sail_test::SAIL_TEST'
export METHOD='0x9af1bff168d5155c2628a29ea17e7012353d94bf7173900461143d096079d96e::minter::mint_test_sail'
export PUBLISHER='0xc8f1a6f24d265297be826001677ac5d2209070f7f3b8d17f7ccbd075c289a3f3'
export MINTER='0xb145981a29c220d8ac1523a512f423eeedce0b71279c7aca0ec005642a1f7431'
export CLOCK=0x6
sui client ptb \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin0 \
--transfer-objects '[coin0]' @0x17733edc639821e8bb24856ba867c60f148115842795d838f1ea1ac67621b275 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin1 \
--transfer-objects '[coin1]' @0x3ce16f18ac7d5b55d8390ab8ca1fd1352701448092d79b503f7cddc7178e2b67 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin2 \
--transfer-objects '[coin2]' @0xedf0529e33e619b1758a0c9805ad85982e1028a2be4668a287e679e33d110437 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin3 \
--transfer-objects '[coin3]' @0xb814555f48adb1c059d812a72bcce52723f331a59cfd08ced4fc0628973096ab \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin4 \
--transfer-objects '[coin4]' @0xe17aba9272bfbd1191f1ac9d7c58de821c084dd57fb83d97f03768423d8efead \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin5 \
--transfer-objects '[coin5]' @0xeb5baeba996eeeca9e8d7d39f9f7ee52979e40135fb2e937f9440390adc58643 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin6 \
--transfer-objects '[coin6]' @0xfbc49d25108333d1c32917152cb9933df8d27f12118d8867e9c4fdaf938643eb \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin7 \
--transfer-objects '[coin7]' @0xf495f0905b7840253cf9e9e8da0f54ee4cb09d4e16f2dd3d9c316a7aded47f6e \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin8 \
--transfer-objects '[coin8]' @0x1d2023acf16513ef589b16adcfe1ed20cee9dccc28b04a8ac2dc517181e8f01e \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin9 \
--transfer-objects '[coin9]' @0x0a656cfc0119de6099054731325e011fe9ecb6eb69ef09d1985659629cbfcf3a \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin10 \
--transfer-objects '[coin10]' @0x83482b633463b785a2bf7ad8e9891f1469c7109331b9d8eb9c792e7c3d5dcc02 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin11 \
--transfer-objects '[coin11]' @0xe48d3d2227772b2bb401f268396a660e1469df0ddef4f02a5d84d2e8ad0ef3d5 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin12 \
--transfer-objects '[coin12]' @0xe77c20bee5ad24ffd897c6cd2509f4a35b66b5c1fb6665b179b5cc80b71ec25b \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin13 \
--transfer-objects '[coin13]' @0xfad0f7836f84d5db872717b6c776f3bbf36df8db1f81c3e9314f1a864cc02973 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin14 \
--transfer-objects '[coin14]' @0x7aa0c2206ef649591f9b12db3baa4572e01a30727b949f7749fc50e08f5ad784 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 6000000000 @$CLOCK \
--assign coin15 \
--transfer-objects '[coin15]' @0x3db9f8c872acb2d1b6befcb57112bcb1f85ebf306f48d010d6e1fe4230a6f786 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin16 \
--transfer-objects '[coin16]' @0xbe85945a935c5cf71d29bee0144921c3abeb46ee302555c1dd410b24e27a6cb6 \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 4500000000 @$CLOCK \
--assign coin17 \
--transfer-objects '[coin17]' @0x31af1d6b300eb2e779c9ccb9997cceea68ac766878d0d1f85724ac867a586d11
