#!/bin/bash

# This script was generated by distribution_script_generator.py

export TOKEN_TYPE='0xb481310100f9f9b812de1fb45b8e118f69c6b69e59145bef34b2232efdd7a8e5::sail_test::SAIL_TEST'
export METHOD='0xc16f3f27459c77dc77a080b765b3d3492b56b6b3e2f1baf322b1f45da7f7dbba::minter::mint_test_sail'
export PUBLISHER='0xc8f1a6f24d265297be826001677ac5d2209070f7f3b8d17f7ccbd075c289a3f3'
export MINTER='0xb145981a29c220d8ac1523a512f423eeedce0b71279c7aca0ec005642a1f7431'
export CLOCK=0x6

sui client ptb \
--move-call $METHOD "<$TOKEN_TYPE>" @$MINTER @$PUBLISHER 2571426000000 @$CLOCK \
--assign coin0 \
--transfer-objects '[coin0]' @0xc3c7b01f09bfb204f93de85afa0a271e5bfabac31e566f7e997b9a8685f18967