[package]
name = "liquidity_locker"
edition = "2024.beta"

[addresses]
liquidity_locker = "0x0"

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.clmm_pool]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "clmm_pool"
rev = "main"
override = true

[dependencies.integer_mate]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "integer_mate"
rev = "main"
override = true

[dependencies.gauge_cap]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "gauge_cap"
rev = "main"
override = true

[dependencies.price_provider]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "price_provider"
rev = "main"
override = true

[dependencies.locker_cap]
local = "../locker_cap"

[dependencies.Switchboard]
git = "https://github.com/LFBuild/sui.git"
subdir = "on_demand/"
rev = "mainnet"

[dependencies.distribution]
local = "../distribution"

[dependencies.ve]
local = "../ve"

[dev-dependencies.price_monitor]
local = "../price_monitor"
