[package]
name = "distribution"
edition = "2024"

[addresses]
distribution = "0x4e57cf0fd73647d44d2191fbb3028176893c07388d9472df07124fe7f72c0a66"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.clmm_pool]
local = "../clmm_pool"

[dependencies.integer_mate]
local = "../integer_mate"

[dependencies.gauge_cap]
local = "../gauge_cap"

[dependencies.price_provider]
local = "../price_provider"
