[package]
name = "airdrop"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

[dependencies.SuiTears]
git = "https://github.com/LFBuild/suitears.git"
subdir = "contracts"
rev = "main"

[dependencies.ve]
local = "../ve"

[addresses]
airdrop = "0x0"

[dev-dependencies]

[dev-addresses]

