[package]
name = "airdrop"
edition = "2024.beta"

[addresses]
airdrop = "0x6e4182b96a6f0960ff30d52f2ce0133cd182fa8ee5ba2f7cf1cd9d2c2c645edb"

[dev-dependencies]

[dev-addresses]

[dependencies.SuiTears]
git = "https://github.com/LFBuild/suitears.git"
subdir = "contracts"
rev = "main"

[dependencies.ve]
local = "../ve"

[dependencies.voting_escrow]
local = "../voting_escrow"
