source ./export.sh

sui client ptb \
--move-call $PACKAGE::setup_distribution::create "<$FULLSAIL_TOKEN_TYPE>" @$MINTER_PUBLISHER @$VOTER_PUBLISHER @$REWARD_DISTRIBUTOR_PUBLISHER @$VOTING_ESCROW_PUBLISHER @$GLOBAL_CONFIG @$DISTRIBUTION_CONFIG @$ADDR @$TREASURY_CAP @$AGGREGATOR @$CLOCK 
