source ./export.sh

sui client ptb \
--move-call $PACKAGE::minter::activate "<$FULLSAIL_TOKEN_TYPE, $OSAIL1_TYPE>" @$MINTER @$VOTER @$DISTRIBUTION_CONFIG @$MINTER_ADMIN_CAP @$REBASE_DISTRIBUTOR @$OSAIL1_CAP @$OSAIL1_METADATA @$CLOCK