[package]
name = "integrate"
edition = "2024"

[addresses]
integrate = "0xe14acefdc888d3e20fc624693b28c4f47ec7d5c7a1c70632cb29b8389e9bd9e6"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
local = "../move_stl"

[dependencies.clmm_pool]
local = "../clmm_pool"

[dependencies.distribution]
local = "../distribution"

[dependencies.integer_mate]
local = "../integer_mate"

[dependencies.gauge_cap]
local = "../gauge_cap"

[dependencies.price_provider]
local = "../price_provider"
