[package]
name = "integrate"
edition = "2024"

[addresses]
integrate = "0x9e939cf525f812c24b23eee8c819603938465d179d0f8d9ecbfc352350be04f8"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "move_stl"
rev = "dev"
override = true

[dependencies.clmm_pool]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "clmm_pool"
rev = "dev"
override = true

[dependencies.distribution]
local = "../distribution"

[dependencies.integer_mate]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "integer_mate"
rev = "dev"
override = true

[dependencies.gauge_cap]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "gauge_cap"
rev = "dev"
override = true

[dependencies.price_provider]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "price_provider"
rev = "dev"
override = true

[dependencies.liquidity_locker]
local = "../liquidity_locker"

[dependencies.liquidity_soft_locker]
local = "../liquidity_soft_locker"

[dependencies.price_monitor]
local = "../price_monitor"

[dependencies.ve]
local = "../ve"
