[package]
name = "integrate"
edition = "2024"

[addresses]
integrate = "0xacc8732610118a1ffe900849190b3b33fb1f632855f4287f5e9fcbfa3f1ae43d"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
local = "../move_stl"

[dependencies.clmm_pool]
local = "../clmm_pool"

[dependencies.distribution]
local = "../distribution"

[dependencies.integer_mate]
local = "../integer_mate"

[dependencies.gauge_cap]
local = "../gauge_cap"

[dependencies.price_provider]
local = "../price_provider"
