[package]
name = "integrate"
edition = "2024"

[addresses]
integrate = "0x58263a1a0da01d0ebcb4f61c3dd2ff057bb2fb0bc1cc856ae121d1344ef9461b"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "move_stl"
rev = "main"
override = true

[dependencies.clmm_pool]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "clmm_pool"
rev = "main"
override = true

[dependencies.governance]
local = "../governance"

[dependencies.integer_mate]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "integer_mate"
rev = "main"
override = true

[dependencies.gauge_cap]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "gauge_cap"
rev = "main"
override = true

[dependencies.price_provider]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "price_provider"
rev = "main"
override = true

[dependencies.price_monitor]
local = "../price_monitor"

[dependencies.voting_escrow]
local = "../voting_escrow"
