[package]
name = "integrate"
edition = "2024"

[addresses]
integrate = "0xf8e0ee7ad790a47acba203428ca0ee728d15ccdd7ab91000044aa884eb73f083"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
git = "https://github.com/LFBuild/FullSail-SC.git"
subdir = "move_stl"
rev = "main"
override = true

[dependencies.clmm_pool]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "clmm_pool"
rev = "main"
override = true

[dependencies.distribution]
git = "https://github.com/LFBuild/FullSail-SC.git"
subdir = "distribution"
rev = "main"
override = true

[dependencies.integer_mate]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "integer_mate"
rev = "main"
override = true

[dependencies.gauge_cap]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "gauge_cap"
rev = "main"
override = true

[dependencies.price_provider]
git = "https://github.com/LFBuild/FullSail-SC.git"
subdir = "price_provider"
rev = "main"
override = true
